+incdir+${WORK_HOME}/tb
${WORK_HOME}/verilog/sys_defs.svh 
${WORK_HOME}/verilog/ISA.svh 
${WORK_HOME}/verilog/xbar.sv
${WORK_HOME}/verilog/mux_onehot.sv
${WORK_HOME}/verilog/onehot_enc.sv
${WORK_HOME}/verilog/rs1.sv
${WORK_HOME}/verilog/rs_array.sv
${WORK_HOME}/verilog/rs_bank.sv
${WORK_HOME}/verilog/wand_sel.v
${WORK_HOME}/verilog/psel_gen.v
${WORK_HOME}/verilog/sort.sv
${WORK_HOME}/verilog/prf.sv
${WORK_HOME}/verilog/backend.sv
${WORK_HOME}/verilog/alu.sv
${WORK_HOME}/verilog/agu.sv
${WORK_HOME}/verilog/bru.sv
${WORK_HOME}/verilog/mult.sv
${WORK_HOME}/verilog/mult_top.sv
${WORK_HOME}/verilog/fu_top.sv
${WORK_HOME}/verilog/decode_rename.sv
${WORK_HOME}/verilog/decoder_top.sv
${WORK_HOME}/verilog/decoder.sv
${WORK_HOME}/verilog/rat.sv
${WORK_HOME}/verilog/free_list.sv
${WORK_HOME}/verilog/busy_table.sv
${WORK_HOME}/verilog/rob.sv
${WORK_HOME}/verilog/arch_rat.sv
${WORK_HOME}/verilog/ptab.sv
${WORK_HOME}/verilog/stq.sv
${WORK_HOME}/verilog/ldq.sv
${WORK_HOME}/verilog/ldq_conservative.sv
${WORK_HOME}/verilog/lsq.sv
${WORK_HOME}/tb/test_backend.sv
